apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: forge-data
    labels:
      provider: fabric8
      project: fabric8-forge
      group: io.fabric8.devops.apps
  spec:
    capacity:
      storage: 20Gi
    accessModes:
    - ReadWriteMany
    nfs:
      path: /data/nfs/volumes/fabric8-data/fabric8-forge
      server: 172.16.5.58
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      provider: fabric8
      project: fabric8-forge
      group: io.fabric8.devops.apps
    name: forge-data
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
    volumeName: forge-data

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: m2data
    labels:
      provider: fabric8
      project: fabric8-forge
      group: io.fabric8.devops.apps
  spec:
    capacity:
      storage: 20Gi
    accessModes:
    - ReadWriteMany
    nfs:
      path: /data/nfs/volumes/fabric8-data/m2data
      server: 172.16.5.58
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      provider: fabric8
      project: fabric8-forge
      group: io.fabric8.devops.apps
    name: m2data
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
    volumeName: m2data
