---

#- include: fetch-scripts.yml

- hosts: nodes
  become: no
  gather_facts: no
  tasks:
  - name: add insecure registry
    shell: sed -i '/INSECURE_REGISTRY=.*/c\INSECURE_REGISTRY="--selinux-enabled --insecure-registry 172.30.0.0/16 --insecure-registry docker-registry-default.172.16.5.60.nip.io --insecure-registry 172.16.5.60:5000"' /etc/sysconfig/docker

  - name: add default registry
    shell: sed -i '/ADD_REGISTRY=.*/c\ADD_REGISTRY="--add-registry docker-registry-default.172.16.5.60.nip.io --add-registry 172.16.5.60:5000"' /etc/sysconfig/docker 

#  - name: docker login
#    shell: 
  - name: restart docker
    systemd: name=docker state=restarted
#  - name: docker login
#    shell:   
