apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: kafka-cluster
    component: kafka-broker-cluster
  name: kafka-broker-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-cluster
        component: kafka-broker-cluster
    spec:
      containers:
      - name: kafka-cluster
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
          - name: ENABLE_AUTO_EXTEND
            value: "true"
          - name: KAFKA_RESERVED_BROKER_MAX_ID
            value: "999999999"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
          - name: KAFKA_CREATE_TOPICS
            value: topic1:16:1
