---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      fabric8.io/app-menu: "development"
      fabric8.io/git-commit: "38d204abfadd191177f09dd272dac38273a66b07"
      fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/sonarqube/src/main/fabric8/icon.svg"
      fabric8.io/git-branch: "release-v2.2.288"
      fabric8.io/build-id: "1"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/38d204abfadd191177f09dd272dac38273a66b07"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/1"
    labels:
      provider: "fabric8"
      expose: "true"
      project: "sonarqube"
      version: "2.2.288"
      group: "io.fabric8.devops.apps"
    name: "sonarqube"
  spec:
    ports:
    - port: 80
      targetPort: 9000
    selector:
      name: "sonarqube"
      project: "sonarqube"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/git-commit: "38d204abfadd191177f09dd272dac38273a66b07"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=sonarqube&var-version=2.2.288"
      fabric8.io/build-id: "1"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/1"
      fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/sonarqube/src/main/fabric8/icon.svg"
      fabric8.io/git-branch: "release-v2.2.288"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/38d204abfadd191177f09dd272dac38273a66b07"
    labels:
      name: "sonarqube"
      provider: "fabric8"
      project: "sonarqube"
      version: "2.2.288"
      group: "io.fabric8.devops.apps"
    name: "sonarqube"
  spec:
    replicas: 1
    selector:
      name: "sonarqube"
      project: "sonarqube"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "38d204abfadd191177f09dd272dac38273a66b07"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=sonarqube&var-version=2.2.288"
          fabric8.io/build-id: "1"
          fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/1"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/sonarqube/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.288"
          fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/38d204abfadd191177f09dd272dac38273a66b07"
        labels:
          name: "sonarqube"
          provider: "fabric8"
          project: "sonarqube"
          version: "2.2.288"
          group: "io.fabric8.devops.apps"
        name: "sonarqube"
      spec:
        containers:
        - env:
          - name: "DB_PORT_3306_TCP_ADDR"
            value: "localhost"
          image: "tpires/sonar-server"
          name: "sonarqube-server-container"
          ports:
          - containerPort: 9000
            name: "cslistener"
            protocol: "TCP"
        - image: "tpires/sonar-mysql"
          name: "sonarqube-database-container"
          ports:
          - containerPort: 3306
            name: "mysql"
            protocol: "TCP"
    triggers:
    - type: "ConfigChange"
