apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/iconUrl: >-
      https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png
    fabric8.io/git-commit: d7165b990bc832be95ed52a61db6bcca857068d9
    fabric8.io/metrics-path: >-
      dashboard/file/kubernetes-pods.json/?var-project=zookeeper&var-version=2.2.157
    fabric8.io/build-id: '3'
    fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
    fabric8.io/git-branch: release-v2.2.157
    fabric8.io/git-url: >-
      http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/d7165b990bc832be95ed52a61db6bcca857068d9
  labels:
    provider: fabric8
    project: zookeeper
    version: 2.2.157
    group: io.fabric8.ipaas.apps
    serverId: '1'
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: fabric8
      project: zookeeper
      group: io.fabric8.ipaas.apps
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: d7165b990bc832be95ed52a61db6bcca857068d9
        fabric8.io/metrics-path: >-
          dashboard/file/kubernetes-pods.json/?var-project=zookeeper&var-version=2.2.157
        fabric8.io/build-id: '3'
        fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
        fabric8.io/iconUrl: >-
          https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png
        fabric8.io/git-branch: release-v2.2.157
        fabric8.io/git-url: >-
          http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/d7165b990bc832be95ed52a61db6bcca857068d9
      labels:
        provider: fabric8
        project: zookeeper
        version: 2.2.157
        group: io.fabric8.ipaas.apps
    spec:
      containers:
        - env:
            - name: ENSEMBLE_SIZE
              value: '1'
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: 'fabric8/zookeeper:2.2.157'
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
              name: zkclient
            - containerPort: 8778
              name: jolokia
          resources:
            limits:
              cpu: '0'
              memory: '0'
            requests:
              cpu: '0'
              memory: '0'
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /opt/zookeeper/data
              name: data
              readOnly: false
            - mountPath: /opt/zookeeper/log
              name: log
              readOnly: false
      volumes:
        - emptyDir:
            medium: Memory
          name: data
        - emptyDir:
            medium: Memory
          name: log
endGroup: false
newGroup: true

