apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: >-
      https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/kafka/src/main/fabric8/icon.png
    fabric8.io/git-commit: d7165b990bc832be95ed52a61db6bcca857068d9
    fabric8.io/git-branch: release-v2.2.157
    fabric8.io/build-id: '3'
    fabric8.io/git-url: >-
      http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/d7165b990bc832be95ed52a61db6bcca857068d9
    fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
  labels:
    provider: fabric8
    project: kafka
    version: 2.2.157
    group: io.fabric8.ipaas.apps
  name: kafka
spec:
  ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    project: kafka
    provider: fabric8
    group: io.fabric8.ipaas.apps
  type: LoadBalancer
endGroup: true
newGroup: true
